services:
  fl-ebank-discovery-service:
    build: ./discovery-service
    container_name: fl-ebank-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 4

  fl-ebank-config-service:
    build: ./config-server
    container_name: fl-ebank-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/actuator/health"]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://fl-ebank-discovery-service:8761/eureka
    depends_on:
      fl-ebank-discovery-service:
        condition: service_healthy

  fl-customer-service:
    build: ./customer-service
    container_name: fl-customer-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://fl-ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://fl-ebank-config-service:9999
    depends_on:
      fl-ebank-config-service:
        condition: service_healthy

  fl-account-service:
    build: ./account-service
    container_name: fl-account-service
    ports:
      - '8083:8083'
    expose:
      - '8083'
    environment:
      - DISCOVERY_SERVICE_URL=http://fl-ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://fl-ebank-config-service:9999
    depends_on:
      fl-customer-service:
        condition: service_healthy

  fl-gateway-service:
    build: ./gateway-service
    container_name: fl-gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://fl-ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://fl-ebank-config-service:9999
    depends_on:
      fl-ebank-config-service:
        condition: service_healthy

  fl-ms-angular-frontend:
    build: ./angular-front-end
    container_name: fl-ms-angular-frontend
    ports:
      - '80:80'
    expose:
      - '80'
