spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri: http://localhost8082/
          predicates:
            - Path=/customers/**
        - id: r2
          uri: http://localhost8083/
          predicates:
            - Path=/accounts/**
  application:
    name: gateway-service
server:
  port: 8888
